# Generated by Django 4.2.27 on 2026-01-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20260108_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('Marcado', 'Marcado'), ('Em Serviço', 'Em Serviço'), ('Concluido', 'Aguardando Pagamento'), ('Finalizado', 'Finalizado (Pago)'), ('Cancelado', 'Cancelado')], default='Marcado', max_length=20),
        ),
    ]
